name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

  workflow_dispatch:
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0

      - name: Install and run Cypress tests
        uses: cypress-io/github-action@v5
        continue-on-error: true
